### ISSUE TITLE
当 TextField 在 onChanged 事件中调用 setState 更新数据时，点击 input 其他区域无法失去焦点

### ISSUE THREAD

**Issue by bluescurry** [gzlock/flutter_focus_widget#1]
如题，感觉是个 bug

**Comment by gzlock** [comment]
如果用的是FocusWidget.builder方法，setState每调用一次，会令到FocusWidget.builder方法创建一个新的FocusNode，会导致出现奇怪的问题。
你这种需求，应该自建FocusNode，再传给FocusWidget和TextField，让FocusWidget和TextField一直都使用同一个FocusNode，参考
```dart
FocusWidget(
    focusNode: myFocusNode, // <===
    child: TextField(focusNode: myFocusNode), // <===
);
```
更具体的代码：
https://github.com/gzlock/flutter_focus_widget/blob/56a3d6f8b29499a1c9febf25c76b5313c085ec69/example/lib/main.dart#L41
https://github.com/gzlock/flutter_focus_widget/blob/56a3d6f8b29499a1c9febf25c76b5313c085ec69/example/lib/main.dart#L120-L130
也可以直接克隆这个仓库到本地，然后用example的代码进行测试，我测试过是没问题的(指这种用法)

**Comment by bluescurry** [comment]
> 如果用的是FocusWidget.builder方法，setState每调用一次，会令到FocusWidget.builder方法创建一个新的FocusNode，会导致出现奇怪的问题。
> 你这种需求，应该自建FocusNode，再传给FocusWidget和TextField，让FocusWidget和TextField一直都使用同一个FocusNode，参考
> 
> ```dart
> FocusWidget(
>     focusNode: myFocusNode, // <===
>     child: TextField(focusNode: myFocusNode), // <===
> );
> ```
> 
> 更具体的代码：
> https://github.com/gzlock/flutter_focus_widget/blob/56a3d6f8b29499a1c9febf25c76b5313c085ec69/example/lib/main.dart#L41
> 
> 
> https://github.com/gzlock/flutter_focus_widget/blob/56a3d6f8b29499a1c9febf25c76b5313c085ec69/example/lib/main.dart#L120-L130
> 
> 
> 也可以直接克隆这个仓库到本地，然后用example的代码进行测试，我测试过是没问题的(指这种用法)

解决了，多谢，确实是我用法的问题
